web:
  build: .
  links:
    - db
    - smtp
  container_name: hipay-mirakl-running
  volumes:
    - .:/var/www/html
  ports:
    - "8080:80"

db:
  image: mysql
  container_name: hipay-mirakl-db-running
  ports:
    - "43306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: app

smtp:
  image: schickling/mailcatcher
  container_name: hipay-mirakl-smtp-running
  ports:
    - "1080:1080"
